services:
- type: pserv
  name: pgbouncer
  env: docker
  plan: standard
  repo: https://github.com/render-oss/docker-pgbouncer
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: POOL_MODE
    value: transaction
  - key: AUTH_TYPE
    value: scram-sha-256
  # NOTE(steve) only useful in session pool mode
  # - key: SERVER_RESET_QUERY
  #   value: DISCARD ALL
  - key: MAX_CLIENT_CONN
    value: 5
  - key: DEFAULT_POOL_SIZE
    value: 3